# This workflow will do a clean installation of node dependencies,  build the source code and run tests across different versions of node

name: ci

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository 🛎
      uses: actions/checkout@v3
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm ci

    - name: Run Prettier 💅
      run: npm run format:check

    - name: Run ESLint 
      run: npm run lint
    
    - name: Run unit tests 🧪
      run: npm test
    
    - name: Setup and run Cypress
      uses: cypress-io/github-action@v2
      with:
          browser: chrome
          headless: true
          start: npm start

    - name: Run build
      run: npm run build --if-present
